services:
  photogrio-server:
    container_name: photogrio-server
    build: ./
    ports:
      - 5001:5001
      - 40000:40000
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    environment:
      - MYSQL_USER=photogrioapi
      - MYSQL_PASSWORD = irishvrlr30
      - MYSQL_DATABASE = photogriodb
      - HOST_NAME = db
    command: /dlv --headless --listen=:40000 --api-version=2 exec /photogrio/server
    depends_on:
      - db
  db:
    container_name: photogriodb
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_USER=photogrioapi
      - MYSQL_PASSWORD=irishvrlr30
      - MYSQL_DATABASE=photogriodb
      - MYSQL_ROOT_PASSWORD=irishvrlr30
    volumes:
      - photogrio-data:/var/lib/mysql

volumes:
  photogrio-data: