services:
  photogrio-server:
    container_name: photogrio-server
    build: ./account.api
    ports:
      - 5001:5001
      - 40000:40000
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    environment:
      - DB_HOST_NAME=photogriodb
      - MYSQL_USER=photogrioapi
      - MYSQL_PASSWORD = irishvrlr30
      - MYSQL_DATABASE = photogriodb
      - AUTH0_APP_DOMAIN=https://photogrio.auth0.com/
      - AUTH0_APP_AUDIENCE=https://photogrio.com
      - AUTH0_DOMAIN=login.photogrio.com
      - AUTH0_AUDIENCE=https://photogrio.auth0.com/api/v2/
      - AUTH0_API_AUDIENCE=https://photogrio.auth0.com/api/v2/
      - AUTH0_AUTHORIZATION_URI=https://photogrio.auth0.com/oauth/token
      - AUTH0_CLIENT_ID=ddlJicrbYRznyfMJVLMqnRkRfloQOPFh
      - AUTH0_CLIENT_SECRET=Z5Y7Y5s-mx95mY7n7ZUca9Omyx_kSdi73-YnhaMJWwI_I27xmqkAZwJbzDPC_YIe
      - AUTH0_CONNECTION=Photogrio
      - SESSION_KEY=WwifweIkwi@#9sk!Ikewoqeo#4kfiwle
    command: /dlv --headless --listen=:40000 --api-version=2 exec /photogrio/server
    depends_on:
      - db
  contact-api:
    container_name: contact-api
    build: ./contacts.api
    ports:
      - 5002:5002
      - 40001:40001
    environment:
      - HOST_NAME=photogriodb
      - MYSQL_USER=photogrioapi
      - MYSQL_PASSWORD=irishvrlr30
      - MYSQL_DATABASE=photogriodb
      - AUTH0_AUDIENCE=https://photogrio.com
      - AUTH0_DOMAIN=https://photogrio.auth0.com/
      - AUTH0_API_AUDIENCE=https://photogrio.auth0.com/api/v2/
      - AUTH0_AUTHORIZATION_URI=https://photogrio.auth0.com/oauth/token
      - AUTH0_CLIENT_ID=c5YZyJhvga3C8TauRo2eZQvUdh6Q6ZeR
      - AUTH0_CLIENT_SECRET=T4fE7yzbilvUdgmI9ZyS3WA436r0kaULVrClFTBS_dCk17YgS0TDayAq_3EuMhfi
      - SESSION_KEY=WwifweIkwi@#9sk!Ikewoqeo#4kfiwle
    command: /dlv --headless --listen=:40001 --api-version=2 exec /contact-api/server
    depends_on:
      - db

  db:
    container_name: photogriodb
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_USER=photogrioapi
      - MYSQL_PASSWORD=irishvrlr30
      - MYSQL_DATABASE=photogriodb
      - MYSQL_ROOT_PASSWORD=irishvrlr30
    volumes:
      - photogrio-data:/var/lib/mysql

volumes:
  photogrio-data: