services:
  photogrio-server:
    container_name: photogrio-server
    build: photogrio.server
    ports:
      - 5001:5001
      - 40000:40000
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    restart: always
    environment:
      - ENVIRONMENT=development
      - DB_HOST_NAME=photogriodb
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD = ${MYSQL_PASSWORD}
      - MYSQL_DATABASE = photogriodb
      - AUTH0_APP_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_APP_AUDIENCE=${AUTH0_APP_AUDIENCE}
      - AUTH0_DOMAIN=${AUTH0_LOGIN_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_API_AUDIENCE}
      - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
      - AUTH0_AUTHORIZATION_URI=https://photogrio.auth0.com/oauth/token
      - AUTH0_CLIENT_ID=${AUTH0_LOGIN_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_ACCOUNT_SECRET}
      - AUTH0_CONNECTION=Photogrio
      - SESSION_KEY=${SESSION_KEY}
      - W_API_KEY=${W_API_KEY}
      - URL_BASE=https://localhost:5001
    command: /dlv --headless --listen=:40000 --api-version=2 exec /photogrio/server
    volumes:
      - photogrio-images:/photogrio/images
      - photogrio-logs:/photogrio/logs
    depends_on:
      - db
  db:
    container_name: photogriodb
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=photogriodb
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - photogrio-data:/var/lib/mysql

volumes:
  photogrio-data:
  photogrio-logs:
  photogrio-images: