services:
  photogrio-server:
    container_name: photogrio-server
    build: ./account.api
    ports:
      - 5001:5001
      - 40000:40000
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    environment:
      - DB_HOST_NAME=photogriodb
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD = ${MYSQL_PASSWORD}
      - MYSQL_DATABASE = photogriodb
      - AUTH0_APP_DOMAIN=https://photogrio.auth0.com/
      - AUTH0_APP_AUDIENCE=${AUTH0_APP_AUDIENCE}
      - AUTH0_DOMAIN=${AUTH0_LOGIN_DOMAIN}
      - AUTH0_AUDIENCE=https://photogrio.auth0.com/api/v2/
      - AUTH0_API_AUDIENCE=https://photogrio.auth0.com/api/v2/
      - AUTH0_AUTHORIZATION_URI=https://photogrio.auth0.com/oauth/token
      - AUTH0_CLIENT_ID=ddlJicrbYRznyfMJVLMqnRkRfloQOPFh
      - AUTH0_CLIENT_SECRET=${AUTH0_ACCOUNT_SECRET}
      - AUTH0_CONNECTION=Photogrio
      - SESSION_KEY=${SESSION_KEY}
    command: /dlv --headless --listen=:40000 --api-version=2 exec /photogrio/server
    depends_on:
      - db
  contact-api:
    container_name: contact-api
    build: ./contacts.api
    ports:
      - 5002:5002
      - 40001:40001
    environment:
      - CONTACTS_API_ENV=development
      - HOST_NAME=photogriodb
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=photogriodb
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
      - AUTH0_AUTHORIZATION_URI=${AUTH0_AUTHORIZATION_URI}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - SESSION_KEY=${SESSION_KEY}
      - USE_SSL=false
      - URL_BASE=http://localhost:5002
    command: /dlv --headless --listen=:40001 --api-version=2 exec /contact-api/server
    volumes:
      - contact-logs:/contact-api/logs
      - contact-images:/contact-api/images
    depends_on:
      - db

  db:
    container_name: photogriodb
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=photogriodb
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - photogrio-data:/var/lib/mysql

volumes:
  photogrio-data:
  contact-logs:
  contact-images: